version: "3.8"

services:
  web:
    container_name: invoice-app
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    environment:
      - PORT=3000
      - API_PORT=8080
    ports:
      - "3000:3000"
    links:
      - db
    depends_on:
      db:
        condition: service_healthy

  api:
    container_name: invoice-app-api
    build:
      context: ./backend/
      dockerfile: Dockerfile
    environment:
      - HTTP-PORT=8080
      - HTTP-HOST=localhost
      - HTTP-READTIMEOUT=30
      - HTTP-WRITETIMEOUT=30
      - POSTGRES-HOST=db
      - POSTGRES-PORT=5432
      - POSTGRES-USER=postgres
      - POSTGRES-DBNAME=postgres
      - POSTGRES-PASSWORD=qwerty
      - POSTGRES-SSLMODE=disable
      - JWT_SALT=asdijdasd102ke1p1x92i0123s13
    ports:
      - "8080:8080"
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
  
  db:
    image: postgres:latest
    container_name: invoice-app-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=postgres
    ports:
      - "5436:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U postgres -d postgres
      interval: 5s
      timeout: 3s
      retries: 5


volumes:
  postgres-db: